- name: Install dependencies for Python build
  yum:
    name:
      - gcc
      - openssl-devel
      - bzip2-devel
      - libffi-devel
      - wget
      - make
    state: present

- name: Download Python 3.11 source
  get_url:
    url: https://www.python.org/ftp/python/3.11.9/Python-3.11.9.tgz
    dest: /usr/src/Python-3.11.9.tgz

- name: Extract Python source
  unarchive:
    src: /usr/src/Python-3.11.9.tgz
    dest: /usr/src/
    remote_src: yes

- name: Build and install Python 3.11
  shell: |
    cd /usr/src/Python-3.11.9
    ./configure --enable-optimizations
    make altinstall
  args:
    creates: /usr/local/bin/python3.11