
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: custom-alerts
  namespace: monitoring
  labels:
    release: monitoring
spec:
  groups:
    - name: pod-alerts
      rules:
        - alert: HighPodCpuUsage
          expr: sum(rate(container_cpu_usage_seconds_total{image!="", container!="POD"}[2m])) by (pod) > 0.8
          for: 1m
          labels:
            severity: warning
          annotations:
            summary: "High CPU usage on pod"
            description: "Pod {{ $labels.pod }} is using more than 80% CPU"

        - alert: HighPodMemoryUsage
          expr: sum(container_memory_usage_bytes{image!="", container!="POD"}) by (pod) / sum(machine_memory_bytes) by (node) > 0.8
          for: 1m
          labels:
            severity: warning
          annotations:
            summary: "High memory usage on pod"
            description: "Pod {{ $labels.pod }} is using more than 80% memory"
