- name: Setup Jenkins EC2 and install CloudWatch Agent
  hosts: jenkins
  become: true
  gather_facts: false

  vars:
    ansible_python_interpreter: /usr/local/bin/python3.11

  pre_tasks:
    - name: Ensure Python 3.11 is installed
      import_tasks: ../roles/jenkins/tasks/install_python.yml

  roles:
    - jenkins
    - cloudwatch
