- name: Full Jenkins EC2 Setup with Required DevOps Tools
  hosts: jenkins
  become: yes

  tasks:
    - name: Remove Java 11 if installed
      command: yum remove -y java-11-amazon-corretto
      ignore_errors: yes

    - name: Import Corretto GPG key
      rpm_key:
        key: https://yum.corretto.aws/corretto.key
        state: present

    - name: Add Corretto repository
      get_url:
        url: https://yum.corretto.aws/corretto.repo
        dest: /etc/yum.repos.d/corretto.repo

    - name: Install Java 17 and other dependencies
      command: yum install -y java-17-amazon-corretto git wget curl unzip docker

    - name: Set Java 17 as default
      shell: |
        alternatives --install /usr/bin/java java /usr/lib/jvm/java-17-amazon-corretto.x86_64/bin/java 20000
        alternatives --set java /usr/lib/jvm/java-17-amazon-corretto.x86_64/bin/java
      args:
        executable: /bin/bash

    - name: Enable and start Docker
      service:
        name: docker
        enabled: yes
        state: started

    - name: Add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Add Jenkins repo
      get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo

    - name: Import Jenkins GPG key
      rpm_key:
        state: present
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key

    - name: Install Jenkins
      command: yum install -y jenkins

    - name: Restart Jenkins with retry
      shell: systemctl daemon-reexec && systemctl restart jenkins
      register: jenkins_restart
      retries: 3
      delay: 10
      until: jenkins_restart.rc == 0

    - name: Install or update AWS CLI v2
      shell: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip -o awscliv2.zip
        ./aws/install --update
      args:
        chdir: /tmp


    - name: Install Helm (with PATH fix)
      shell: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
        export PATH=$PATH:/usr/local/bin
        echo 'export PATH=$PATH:/usr/local/bin' >> /etc/profile
      args:
        executable: /bin/bash

    - name: Install kubectl
      shell: |
        curl -o kubectl https://amazon-eks.s3.us-east-1.amazonaws.com/latest/bin/linux/amd64/kubectl
        chmod +x ./kubectl
        mv ./kubectl /usr/local/bin

    - name: Install Trivy
      shell: |
        rpm -ivh https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.50.1_Linux-64bit.rpm

    - name: Install SonarScanner CLI
      shell: |
        wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip -O /tmp/sonar-scanner.zip
        unzip /tmp/sonar-scanner.zip -d /opt/
        ln -s /opt/sonar-scanner-5.0.1.3006-linux /opt/sonar-scanner
        echo 'export PATH=$PATH:/opt/sonar-scanner/bin' >> /etc/profile
