
- hosts: all
  become: yes
  tasks:
    - name: Install Java
      package:
        name: java-11-amazon-corretto
        state: present

    - name: Add Jenkins repo key
      rpm_key:
        state: present
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key

    - name: Add Jenkins repository
      get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo

    - name: Install Jenkins
      package:
        name: jenkins
        state: present

    - name: Start Jenkins
      service:
        name: jenkins
        state: started
        enabled: yes

    - name: Open port 8080
      firewalld:
        port: 8080/tcp
        permanent: true
        state: enabled
        immediate: yes

    - name: Install SonarScanner dependencies
      package:
        name:
          - unzip
          - wget
        state: present

    - name: Download SonarScanner
      get_url:
        url: https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
        dest: /opt/sonar-scanner.zip

    - name: Unzip SonarScanner
      unarchive:
        src: /opt/sonar-scanner.zip
        dest: /opt/
        remote_src: yes

    - name: Symlink SonarScanner
      file:
        src: /opt/sonar-scanner-4.6.2.2472-linux/bin/sonar-scanner
        dest: /usr/bin/sonar-scanner
        state: link

    - name: Download Jenkins CLI
      get_url:
        url: http://localhost:8080/jnlpJars/jenkins-cli.jar
        dest: /tmp/jenkins-cli.jar

    - name: Install Jenkins Plugins
      shell: >
        java -jar /tmp/jenkins-cli.jar -s http://localhost:8080 install-plugin
        git workflow-aggregator ansible docker-plugin kubernetes terraform aws-credentials blueocean sonar -restart
      environment:
        JENKINS_HOME: /var/lib/jenkins
      args:
        executable: /bin/bash
