- name: Install Java (Jenkins dependency)
  raw: |
    sudo yum install -y java-11-openjdk

- name: Add Jenkins repo
  raw: |
    sudo wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo
    sudo rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key

- name: Install Jenkins
  raw: |
    sudo yum install -y jenkins

- name: Start and enable Jenkins service
  raw: |
    sudo systemctl enable jenkins
    sudo systemctl start jenkins
