- name: Enable corretto11 and install Java 11
  raw: |
    sudo amazon-linux-extras enable corretto11
    sudo yum clean metadata
    sudo yum install -y java-11-amazon-corretto

- name: Add Jenkins repo and import GPG key
  raw: |
    sudo wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo
    sudo rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key

- name: Install Jenkins
  raw: |
    sudo yum install -y jenkins

- name: Enable and start Jenkins service
  raw: |
    sudo systemctl enable jenkins
    sudo systemctl start jenkins
